language: java
install: ant deps

sudo: false

jdk:
  - oraclejdk8


script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - echo "compiling files" 
  - mvn test -B
  - echo "running test"
  - ant test	
